### ISSUE TITLE
Error in dataset: index of the target word does not agree with the target word itself

### ISSUE THREAD

**Issue by adno** [luxinyu1/Chinese-LS#2]
Line 50 of the dataset specifies target word "莫名其妙" and target word index 1, but the actual word at index 1 is "可怕". It seems that the target word is correct and the target word index should be corrected to 9. It is the only item in the dataset with this problem.

https://github.com/luxinyu1/Chinese-LS/blob/363bbc482e72caae35ed71cf09e49f3b2b087999/dataset/annotation_data.csv#L50

**Comment by luxinyu1** [comment]
Thanks for this issue, we will fix it recently.
